"""Render compiled endpoints + external-endpoint declarations into Gatus YAML."""

from __future__ import annotations

from datetime import datetime, timezone

import yaml


def _sort_key(item: dict):
    return (item.get("group", ""), item.get("name", ""))


def _payload(endpoints, external_endpoints) -> dict:
    doc = {}
    if endpoints:
        doc["endpoints"] = sorted(endpoints, key=_sort_key)
    if external_endpoints:
        doc["external-endpoints"] = sorted(external_endpoints, key=_sort_key)
    return doc


def render(endpoints, external_endpoints=None, generated_by: str = "autogatus") -> str:
    """Standalone Gatus config document. Lives beside the hand-written base
    config in the config directory; Gatus merges and hot-reloads."""
    doc = _payload(endpoints or [], external_endpoints or [])
    stamp = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    n_ep = len(doc.get("endpoints", []))
    n_ext = len(doc.get("external-endpoints", []))
    header = (
        f"# Generated by {generated_by}. DO NOT EDIT.\n"
        f"# Source of truth is the gatus.* labels + monitored containers.\n"
        f"# endpoints: {n_ep}  external-endpoints: {n_ext}  |  rendered: {stamp}\n"
    )
    if not doc:
        return header + "endpoints: []\n"
    return header + yaml.safe_dump(doc, sort_keys=False, default_flow_style=False, width=100)


def render_stable(endpoints, external_endpoints=None) -> str:
    """Timestamp-free rendering for change detection. Two identical clusters
    must compare equal so an idle cluster never rewrites the file."""
    doc = _payload(endpoints or [], external_endpoints or [])
    if not doc:
        return "endpoints: []\n"
    return yaml.safe_dump(doc, sort_keys=False, default_flow_style=False, width=100)
