"""Render compiled endpoint dicts into a Gatus config YAML document."""

from __future__ import annotations

from datetime import datetime, timezone

import yaml


def _sort_key(endpoint: dict):
    return (endpoint.get("group", ""), endpoint.get("name", ""))


def render(endpoints: list, generated_by: str = "autogatus") -> str:
    """Return a Gatus-compatible YAML document containing ``endpoints``.

    The output is a standalone file meant to live in the Gatus config directory
    alongside the hand-written base config; Gatus merges every ``*.yaml`` there.
    Endpoints are sorted deterministically so an unchanged cluster renders byte
    for byte identically (no churn, no needless Gatus reloads).
    """
    ordered = sorted(endpoints, key=_sort_key)

    stamp = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    header = (
        f"# Generated by {generated_by}. DO NOT EDIT.\n"
        f"# Source of truth is the gatus.* labels on your containers.\n"
        f"# Endpoints: {len(ordered)}  |  rendered: {stamp}\n"
    )

    if not ordered:
        return header + "endpoints: []\n"

    body = yaml.safe_dump(
        {"endpoints": ordered},
        sort_keys=False,
        default_flow_style=False,
        width=100,
    )
    return header + body


def render_stable(endpoints: list, generated_by: str = "autogatus") -> str:
    """Like :func:`render` but without the timestamp line.

    Used for change detection: two clusters that differ only by render time must
    compare equal, otherwise every reconcile would rewrite the file.
    """
    ordered = sorted(endpoints, key=_sort_key)
    if not ordered:
        payload = "endpoints: []\n"
    else:
        payload = yaml.safe_dump(
            {"endpoints": ordered},
            sort_keys=False,
            default_flow_style=False,
            width=100,
        )
    return payload
